### ISSUE TITLE
Incompatability with "Code Spell Checker" extension

### ISSUE THREAD

**Issue by jerone** [ryu1kn/vscode-extension-update-reporter#11]
The changelog from [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) creates an very long update report:

![image](https://user-images.githubusercontent.com/55841/74911393-ca3a5900-53bc-11ea-8347-af6527376c84.png)

Even with it's own headers:
![image](https://user-images.githubusercontent.com/55841/74911419-d7574800-53bc-11ea-84d9-5fc479b25b16.png)

And Markdown rendering issues:
![image](https://user-images.githubusercontent.com/55841/74911434-e2aa7380-53bc-11ea-9d90-aeec8cdf3e36.png)

Possible solutions:
* Ask Code Spell Checker to improve [their changelog](https://marketplace.visualstudio.com/items/streetsidesoftware.code-spell-checker/changelog).
* Detect current version only.
* Render only x amount of lines.
* Collapsible changelog per extension.

**Comment by ryu1kn** [comment]
Thanks @jerone for the helpful screenshots and even possible solutions!

It looks like they've updated their changelog and now the lines that were causing those funny rendering seems to have gone.

To your second point, Extension update reporter reports only the changes that have introduced since you grabbed an older version. i.e. If you have version 1.0.0 of an extesion installed, when it finds 1.2.0, it only reports changes between 1.0 - 1.2, but not changes up to 1.0; it's not only the current version, but I think this is desirable; maybe I skip 1.1 and straight to 1.2, but I still want to see the changes made in 1.1 even though it's not the current version.

Providing the option to limit the number of lines sounds good; but if we had your 4th point, collapsible changelog, we may not need one :+1:

**Comment by jerone** [comment]
@ryu1kn Can we at least add collapsible changelog per extension.

Extensions like ESLint, Code Spell Checker, C# and other don't comply to the standard required for this extension. Making the "Extensions Updates"-page extremely long and unnecessary complex to find updates about other extensions.

Hope you have time to implement this feature. This extension is so useful!

**Comment by jerone** [comment]
Confirmed fixed ✅
